version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  app:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
    env_file:
      - .env
    ports:
      - "81:8000"
    command: uvicorn personal_ai_assistant.api.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=mypia
      - POSTGRES_USER=mypia
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mypia"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A personal_ai_assistant.celery_app worker --loglevel=info
    volumes:
    - ./data:/app/data
    - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - app
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A personal_ai_assistant.celery_app beat --loglevel=info
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - app
      - db
      - redis

  chroma_db:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"

volumes:
  postgres_data:
  redis_data:
  chroma_data:
  static:
